version: "3"

services:
  strapimain:
    image: strapi/strapi
    container_name: strapimain
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-main-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1338:1337"

  mongomain:
    image: mongo:4.4.6
    container_name: mongomain
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-main-network
    volumes:
      - strapimain:/data/db
#    ports:
#      - "27017:27017"

  main:
    build: ./
    container_name: main
    networks:
      - strapi-main-network
    ports:
      - "8084:8084"

networks:
  strapi-main-network:
    driver: bridge

volumes:
  strapimain:
