version: "3"

services:
  strapimf:
    image: strapi/strapi
    container_name: strapimf
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-mf-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mongomf:
    image: mongo:4.4.6
    container_name: mongomf
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-mf-network
    volumes:
      - strapidata:/data/db
#    ports:
#      - "27017:27017"

  mfapp:
    build: ./
    container_name: mfapp
    networks:
      - strapi-mf-network
    ports:
      - "8089:8089"

networks:
  strapi-mf-network:
    driver: bridge

volumes:
  strapidata:
